name: grocery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  retrofit: ^4.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  cached_network_image: ^3.4.1
  dots_indicator: ^4.0.1
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  shimmer: ^3.0.0
  flutter_svg: ^2.2.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^10.0.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins.medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: assets.dart
  field_prefix: null
